### ISSUE TITLE
Get a better logo

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#10]
I don't like the sick emoji enough to use it in the Twitter cards or Facebook OG.

**Comment by Erioldoesdesign** [comment]
I'm working on this :)

**Comment by Erioldoesdesign** [comment]
Here's a .pdf of some sketches worked up in vector.
[Foss-responders-logos.pdf](https://github.com/foss-responders/fossresponders.com/files/4350451/Foss-responders-logos.pdf)

In the spirit of Open Source processes (but sadly not tooling) here's the .ai file so any other designers can play with the file too: https://drive.google.com/file/d/12a7F6epMbgkXFmoBmyEXkTvR_DH7l0kM/view?usp=sharing

**Comment by Memo-Es** [comment]
Hey! 👋🏼

Talking with Alyssa in the Slack channel she also asked for my help with this... I was telling her that I worked a couple of years ago inside a tech weekend regarding the emergency situation of Mexico City's earthquake in 2017. If it works I would gladly donate that design and modify it if needed.

<img width="372" alt="Screen Shot on 2020-03-17 at 14-12-24" src="https://user-images.githubusercontent.com/49539954/76999764-cb5b9900-691c-11ea-9346-08dacefc9fdd.png">

Tell me what you guys think @Erioldoesdesign

**Comment by RichardLitt** [comment]
Thanks, @Memo-Es! While i like it, I think it works better with the name helping hands, and doesn't convert well to Foss responders. 

@Erioldoesdesign Thank you for your time, too! I really like this one:

<img width="295" alt="Screen Shot 2020-03-18 at 15 55 18" src="https://user-images.githubusercontent.com/910753/77001836-f8b24200-6930-11ea-9154-2f942be45150.png">

I think this is pretty much perfect, but I'd want buy-in from others.

**Comment by Erioldoesdesign** [comment]
@Memo-Es Nice logo! but I suppose I don't know who has been given 'design authority' for decisions but I did say in a thread/the channel I'd work on this all today so if it'd been decided you'd work on it I missed that communication?

Should we try to work together on the design side of things? and it'd be nice if someone could clarify whether this project is 'open' or via private conversations or a combo? I don't want to step on toes but I'm getting confused and worried that I'm just not doing the right process to contribute.

**Comment by RichardLitt** [comment]
@Erioldoesdesign We do not have a design authority. The best thing to do would be to bring this up at the meeting tomorrow, I feel, at 1300 EST (1700UTC I think). I can invite you to that, if you don't have an invite already. 

This project is a bit of a mess in terms of delegation - Megan, Duane and I are actively working on that, and compartmentalizing things. I built the website and designed it, so far, but I would really like a logo and more design help in general. I think Alyssa just reached out to @Memo-Es and said we might need help; @Memo-Es, is that right?

**Comment by Memo-Es** [comment]
Yes, @RichardLitt Alyssa mentioned that on Slack. As discussed privately with @Erioldoesdesign my intention is to work collaboratively on open work schemes. It is particularly challenging with design because there are no such frameworks (yet), but speaking specifically of this issue, my idea was that if that logo or any further contribution is useful to solve this problem would love to work with others designers (and non-designers) to find the best option!

Anyway, feel free to ask away for help and/or design advice 😀 we are in this together!

**Comment by awright** [comment]
love them @Erioldoesdesign !! though the one @RichardLitt called out reminds me too much of blockchain -- which has forever changed my read of any decentralized connectivity aesthetic. 

i rather like the more geometric designs as seen here: 

<img width="234" alt="Screen Shot 2020-03-19 at 12 05 33 PM" src="https://user-images.githubusercontent.com/78410/77105110-56e72f80-69da-11ea-87dc-4885971af5cc.png">

i also really appreciate the positivity here:
<img width="242" alt="Screen Shot 2020-03-19 at 12 05 53 PM" src="https://user-images.githubusercontent.com/78410/77105124-5f3f6a80-69da-11ea-9e6a-07859c085df8.png">

i think we are on the right track and for me -- any of these would work. the shared softness and palette of yours and @Memo-Es designs seem aligned.

**Comment by nuritzi** [comment]
Thanks for your help making these @Memo-Es! I'm impressed by how you turned the hand drawn illustrations into digital so quickly. You designers are magicians! :) 

I saw that you added a note to the PDF that said that you were looking for a partner to help. I've contacted someone I know to see if they'd be able to help. Will bring her in this discussion if she has bandwidth. 

I really love your artwork and I'd like to make sure that we have our branding objectives right before we move forward with selecting a logo. 

I know that time is of the essence, but I wonder if we can take a step back and talk about the tone we want to have in our branding. I didn't see this discussed elsewhere, so my apologies if you've already done this exercise. 

## Objectives for tone
These are some adjectives that I think we want represented in our branding: 
 * **Trustworthy.** Since people will be donating money, we want to make sure that we come across as extremely trustworthy. I would argue that we want to avoid being too "fun" or "casual" because we want to establish credibility with our donors.
 * **Approachable.** We want a diverse group of people to feel comfortable approaching us. I think there should be a warmth in our design. 
 * **Inspirational.** We want to inspire people to take action and to help each other out. We want to convey hope and positivity. 

What do others think? Do those objectives align with what others are hoping for? 

Once we have these tone objectives/guidelines, they can help us with the logo design, our tone of voice when writing communications, etc. 


## Inspiration
While I think it's nice to keep in mind open source logos, I think we should also consider how other "first responders" or volunteer orgs brand themselves. Here are some I found online:

![muindi foundation](https://user-images.githubusercontent.com/61520385/77134569-dac60980-6a24-11ea-91c3-5dc98337fc04.jpeg)
![first responders badge](https://user-images.githubusercontent.com/61520385/77134553-d0a40b00-6a24-11ea-951e-b05a8e000f3c.jpeg)
![foursquare disaster relief](https://user-images.githubusercontent.com/61520385/77134562-d4379200-6a24-11ea-98ee-a527a3d5d32e.jpeg)
![habitat for humanity](https://user-images.githubusercontent.com/61520385/77134567-d7cb1900-6a24-11ea-9876-14923c0988ec.jpg)
![red cross](https://user-images.githubusercontent.com/61520385/77134571-dd286380-6a24-11ea-955c-eb99e443b154.png)
![simply giving](https://user-images.githubusercontent.com/61520385/77134575-e0bbea80-6a24-11ea-9abd-0160c6711a40.png)
![unicef-1-1](https://user-images.githubusercontent.com/61520385/77134582-e285ae00-6a24-11ea-8ab2-cffb33932264.jpg)
![volunteers](https://user-images.githubusercontent.com/61520385/77134583-e5809e80-6a24-11ea-8985-397d49248622.png)

I don't think we want to go for this exactly, but I do think we should keep in mind the branding of other established orgs. 

The thing I notice is fewer colors used in the icon and logo. I think that some of these still seem quite warm, approachable, and inclusive, and seem trustworthy because of the simplicity. 

## Other
 * I wonder if it'd be good to have a typeface logo and an icon that can be separated so that we can use them for many different kinds of use cases.

**Comment by DuaneOBrien** [comment]
+1 to finding the right balance of Approachable and Trustworthy.

Of the designs in the PDF, I like the smiling figures and the larger figures the least. They feel closer to a youth-focused initiative. 

This is my favorite of the list so far.

<img width="361" alt="Screen Shot 2020-03-20 at 12 06 03 AM" src="https://user-images.githubusercontent.com/4315550/77143134-85e3bc80-6a3f-11ea-8fe0-85975354e935.png">

Thanks for pushing this forward!

**Comment by Erioldoesdesign** [comment]
@nuritzi the only thing regarding tone that was discussed was via a slack thread that Alyssa started where I asked about the focus beyond the mission statement and I remember receiving friendly and approachable and happy. Along with some imagery from free icon sites.

Logos should always Ideally work in gray/black as well as full-colour scales and that's why these brands above tend to have one to two colours max and no gradients etc. this is mostly for print publications. You can, lean on more colours if you never intend to be print-based and always digital.
Also remember these logos aren't 'new brand's and they've had a long time to build trust and awareness over time :) brands/logos will often mimic or associate with other similar offerings when they want to leech off/supplement that organisations offering which is why you find many similar logos.

I think what I want to be careful of communicating is that we're an 'established organisation' right now (and possibly in the future?) we're a group of folks wanting to help in the ways in which we have capacity and power. A logo that looks too 'NGO' will give a certain impression of competency and also...NGO's have their own...like...assumptions made from them, long application processes, grant structures, red tap, bureaucracy etc. We should think carefully if we want to give off that vibe!

Trying to serve both 'organisations that want to donate' and 'regular people wanting to interact and receive money' is going to be tricky in a single logo. They have fundamentally different things they look for in a design.

So the happy faces' were from Alyssa's suggestion so now I've had two-three people suggest moving away from 'happy faces' I'll steer away from that.

I've been speaking to Marie Nordin on Telegram but she needs to gain access to this repository and the slack group so we aren't branching out comms again.

@Memo-Es ity'd be great if we could sync up somewhen to talk about what we need to do to establish:

- Trust
- Approachable
- Inspirational

Let's also remember that while it's nice to internally like our own logo *we are not our users* :) we should choose and communicate what we think is best for the audience we're serving. Of all the logo's I've made in my many years of designing, most of them are not the ones I liked, but the ones that community/user chose through testing or we decided collectively they communicated the right message (I think y'all probably already know this but just in case anyone hasn't worked in a branding project before)

**Comment by nuritzi** [comment]
@Erioldoesdesign Thanks for the response! Yeah, I agree that we shouldn't have a brand that looks bureaucratic or overly established. 

I also agree that the logo should look good in one color, and in addition, I think it should look good when it's small (so something simple is good rather than overly detailed). 

As I mentioned in chat, I can see if I can pull in another designer if needed (she has really good branding experience), but it seems like we already have a good amount looking into this. 

Thank you again for pushing this initiative forward! :)

**Comment by Erioldoesdesign** [comment]
I was speaking with another designer that was asked to pitch in via a different comms methods and they suggested some logos which were more visually towards using:

Hands, hearts and crosses.

Do we feel strongly for or against including or doing some treatments with hands/hearts/crosses?

**Comment by awright** [comment]
i love the alignment around tone (and the exercise more generally
nuritizi!) and think much of what you sketched eriol captures the 3
anchors. for me i see *Trust* in the organized geometry, *Approachability* in
the color palette; and *Inspiration* in the connection of community.

i would also be happy to see ideas and inspirations from your designer
friend! i will say that what you've already made here is such a
wonderful improvement from where we are currently. I would also be happy to
move forward with your favorite too.

**Comment by Erioldoesdesign** [comment]
Here were the designs from Marie (via telegram messaging)

![IMG_20200323_162301_229](https://user-images.githubusercontent.com/11681324/77340112-bcae2100-6d24-11ea-88c2-b3577d89554a.jpg)

I like the hearts and some of the compositions here but I think it's best we stay away from the cross for several reasons including Red Cross associations, healthcare and religious connotations.

Some more logos will be uploaded tonight (GMT time) taking into account as much of the commentary above :)

**Comment by awright** [comment]
Thank you! And totally agreed. ;)

**Comment by Erioldoesdesign** [comment]
Logo files updated with some developed versions of logos! please check them out :)

https://drive.google.com/open?id=1gZ7yOn8JPCgKeNllx_jvswfcb5RUUXS0

**Comment by rachellawson** [comment]
Agree on staying away from the cross - if only because it is relevant in only a part of the world. (see Red Crescent)

**Comment by awright** [comment]
thanks eriol! they are great! when we’re done with all this can you work in
my own logo? #kidding

i like the 2 attached the most. i think it’s important to have people front
and center.  and i appreciate the lines of connection among them/us. also,
i love the diversity of colors and faces. not first responders, we are FOSS
responders. go team!

**Comment by Erioldoesdesign** [comment]
@awright I think because you replied via email I can't see the attachments you are referencing?

Would you mind adding them again via a browser? thanks!

haha always happy to help folks out with design stuff :)

**Comment by awright** [comment]
ha! sorry about that. here are the 2 i enjoy the most!
![8NCS19v3TbG%OXaqf49ytw_thumb_271a](https://user-images.githubusercontent.com/78410/77551292-66012e00-6e6f-11ea-9ce6-89fd6083c355.jpg)

(let me know if there is any problem.)

**Comment by nuritzi** [comment]
I still think that we need to make sure that the logo is simple and also looks really good when it's small. I think that's the beauty behind logos like Open Collective's. 

![Screen Shot 2020-03-25 at 9 01 33 AM](https://user-images.githubusercontent.com/61520385/77557794-66052c00-6e77-11ea-9cc6-84679fdac367.png)

## For example

### It should fit easily and neatly into a top bar

![Screen Shot 2020-03-25 at 9 03 14 AM](https://user-images.githubusercontent.com/61520385/77557868-7b7a5600-6e77-11ea-9706-12c620c9ca80.png)

 (if we used one of the ones with lots of people, that top bar area would look crowded / you wouldn't be able to distinguish that the icons are people)

### You should be able to use the icon for the favicon
This is the part that shows in the tab. If we have an icon that is too busy, it won't be displayed well. Simple is better, IMO. It needs to look good when really small, and I think it also should be ok to use just the icon in some instances (like the "O" in Open Collective.

![Screen Shot 2020-03-25 at 9 05 26 AM](https://user-images.githubusercontent.com/61520385/77558095-ca27f000-6e77-11ea-8437-161b10d1ce60.png)

### It should look good in one or two colors
I love the detail in the examples you have @awright but I think that it would get lost if we have to use the logo in greyscale. I don't think they are versatile enough for what we need in a logo, although I agree that they're really cute!

### Icons
@Erioldoesdesign did you see the icons that Richard posted about? [Font Awesome released some icons for this COVID-19 response effort](https://community.fossresponders.com/t/font-awesome-has-released-covid-19-response-icons/38). I really like the shield icon in the second-to-bottom row. 

<img width="1015" alt="Screen Shot 2020-03-24 at 5 34 09 PM" src="https://user-images.githubusercontent.com/61520385/77558769-94cfd200-6e78-11ea-8550-5d0979b11380.png">

Out of the new ones that you added, I like this one best because of simplicity: 

![Screen Shot 2020-03-25 at 9 12 04 AM](https://user-images.githubusercontent.com/61520385/77558893-bc269f00-6e78-11ea-87fc-a7d1998d82e6.png)

I think we could use the O with the heart in it as our favicon, and it would look ok in a top bar... although I wonder if it'd be able to get more horizontal (two lines like that might be hard to fit). 

I also think that we could use it in a variety of colors, which would be really cool. 

---

I know that we need to move quickly here, so I don't want to be too disruptive.  I also think it's important that we consider the use cases for the icon, and our branding objectives, even though we're moving quickly. 

Thank you for pushing this forward, @Erioldoesdesign, @awright, and others involved!

**Comment by awright** [comment]
Really good points @nuritzi ! For me, the people in the logo is a really important part of the work. But I empathize with your points and would love to hear from others too! 

I am sure @Erioldoesdesign has much better insight, but to address one of the issues -- what if the favicon was a single/or double person? 
<img width="1027" alt="Screen Shot 2020-03-25 at 9 37 06 AM" src="https://user-images.githubusercontent.com/78410/77561707-4ae8eb00-6e7c-11ea-8cd9-9804aaab7cfc.png">

**Comment by nuritzi** [comment]
@awright  I like what you've done there, and if we decide on that one, I think that's a great favicon to go with :) 

**If we go with this, can we explore:** 
 * How would this style look as a horizontal logo that fits into a top bar? 
 * Will it look good without multiple colors? I think we should consider a logo that looks good with minimal colors (e.g. if you have to print it in black and white only, or if someone adds it to a website to link to us and they have it black and white until you scroll over it, etc). 

The other thing I just thought about is that some people may not know what FOSS is (we're appealing to a broad group of people, right?). Would it make sense to have something that seems a bit more software focused, or has that component? Just a thought, sorry, don't want to derail. It's just that the people, especially when we have just a black and white icon, had me thinking of initiatives and causes totally unrelated to software.

**Comment by Erioldoesdesign** [comment]
There's no reason that something like these:

![image](https://user-images.githubusercontent.com/11681324/77560284-2a895280-6eb5-11ea-99ac-c6b1d1824448.png)

Can't be used as brand/identity devices as well as something like this for a logo:
![image](https://user-images.githubusercontent.com/11681324/77560329-3b39c880-6eb5-11ea-9e68-47de4763978f.png)

All I would say is a heart in an 'o' isn't a unique identity and not memorable or reusable but then again, our project doesn't intend to be around long (I'm talking, 10's of years here) so that's less of an issue.

If we wanted a heart in our identity I would suggest the ones that include hands that I did in the document:
![Screenshot 2020-03-25 at 16 35 19](https://user-images.githubusercontent.com/11681324/77561728-03338500-6eb7-11ea-99ec-107d3c950356.png)

Favicons can be pretty complex, abstract or unique and really, unless you're a website/content stream that will be kept open on a tab a favicon isn't hugely important to a brand:
<img width="573" alt="Screenshot 2020-03-25 at 17 16 46" src="https://user-images.githubusercontent.com/11681324/77565648-72f83e80-6ebc-11ea-8efc-e26df803bf2c.png">

We also don't have a navigation bar and depending on the content of the website we might never. It's good to assume we might but there are ways you can work complex logos into nav bars through progressive enhancement techniques. Here are some of the logos in a navbar orientation where I've reduced complexity for the navbar:

<img width="881" alt="Screenshot 2020-03-25 at 17 23 29" src="https://user-images.githubusercontent.com/11681324/77566318-60323980-6ebd-11ea-87d0-533e0f93b682.png">

Here's some of the logo's in the current layout which is what I thought of when designing:
<img width="945" alt="Screenshot 2020-03-25 at 17 25 38" src="https://user-images.githubusercontent.com/11681324/77566518-ae473d00-6ebd-11ea-8bfa-9aa2823d244e.png">

Grayscale/ black and white is most important and used in print when you don't have access to RGB/CMYK colours or can't afford to have them printed. There is some concern for many colours if we were concerned about kb file size download of logos or if we're overlaying our logo on complex photography/background textures for advertising (which is more likely). I think we can make a B/W logo if we need to for a specific purpose. For now, I really don't recommend we concern ourselves with B/W as we're unlikely to need to go print or do advertising.

To clarify the next steps:

1. Are you saying you want logo designs to include shields? 

2. Are are you saying you like the icons and want to use them across the site or as a logo? (I agree with using across site but probably not for logo. Icons are great to supplement actions and/or text-based commands and serve good purposes in information parsing.)

3. Is there a contender that we can settle on here? or a style that can be adapted as I've shown above in the orientations/sizes?

4. Have I addressed further needs with my responses in regards to colour/favicons etc.?  

I really want to get this ticket done but if it looks like I'm just not getting it right for some reasons then we'll need to find a new/different path forward.

**Comment by Erioldoesdesign** [comment]
Because I've spent around 4 days of my time working on a logo/identity for something and I'm still feeling like I'm spinning in a circle on.

So perhaps I need to hand off to someone who has a different perspective or I need to know, as a designer I can give my informed recommendation on what this should be and go with that?

**Comment by nuritzi** [comment]
@Erioldoesdesign thanks for doing the mockups, that helped a lot. Sorry for any frustration I've caused you, I haven't had as much experience with seeing complex designs get simplified. I think what you and Alyssa showed was really helpful. So, thanks for that!

We do have a case for using the logo in a top bar. We've created a Discourse instance and I'll be presenting to the group how we might use it during tomorrow's meeting. As you can see, the top bar would need a horizontal logo: https://community.fossresponders.com/

In the interest of time, I defer to you and Alyssa to make the decision on which one to move forward with. 

Thanks for taking time to work on this, @Erioldoesdesign. Your work is very appreciated.

**Comment by nuritzi** [comment]
Oh, and I just wanted to add this comment to explicitly respond to the question you asked @Erioldoesdesign  --  seeing the horizontal treatments and how you can simplify the logo according to the medium really helped address some of the considerations I brought up. Thanks!

**Comment by RichardLitt** [comment]
Lots going on in this thread! Thank you, @Erioldoesdesign and @nuritzi and @awright for your work.

> So perhaps I need to hand off to someone who has a different perspective or I need to know, as a designer I can give my informed recommendation on what this should be and go with that?

@Erioldoesdesign: I think you're the most experienced person here with designs, and I love the designs you have (in particular, [these](https://github.com/foss-responders/fossresponders.com/issues/10#issuecomment-603893218)). We do not have anyone who can give a sign off on designs, because this isn't a hierarchy. That having been said, I will fully defer to whatever you decide, and I think what you've got here is great. 

I don't think the logo needs shields, and I don't think we need to use those icons - I just thought they were interesting. I agree that we should use them elsewhere on the site, if that makes sense to do. 

For me: I vote for the designs Alyssa pointed out; I think that color is fine, and bw as necessary; if you @Erioldoesdesign could use your best judgement for making favicons and a horizontal logo, I'll implement them where needed on the website. 

Thank you, again! Excited to push these out and get rid of the current favicon on the website.

**Comment by DuaneOBrien** [comment]
Chiming in a little late on this one this morning with a couple comments.

My clear preference is for this design

![Screen Shot 2020-03-25 at 11 30 10 AM](https://user-images.githubusercontent.com/4315550/77572381-1aa94880-6e8c-11ea-829e-bf2672bd8585.png)

The way the background connections form a sort of safety net really resonated with me. 

@Erioldoesdesign these are great, and I'm really grateful for your work here. I want to endorse @RichardLitt's comments on signoff and decision making - we don't have an established process, and I defer to your judgement.

**Comment by Erioldoesdesign** [comment]
Okay, cool cool, I think in general we like people, connection lines and the large type. 

We can close this ticket as we've picked a good direction to build other logo orientations from and what we really need now are tickets related to specific uses of the logo e.g. 'Logo for discourse' 'logo for  twitter' 'Logo on transparent background for general use'

**Comment by Erioldoesdesign** [comment]
![Logo - 270x790 px](https://user-images.githubusercontent.com/11681324/77836209-23c83d00-714c-11ea-8de8-1cdcaa817739.png)

Here's a standard-ish Logo size at 270x790 px

**Comment by RichardLitt** [comment]
TODO: Add the logo https://drive.google.com/file/d/1BJdkdKyJZb5GMR9s2ZocMXM22ms_HSZh/view?usp=sharing to the website as a header, above the three buttons.
