### ISSUE TITLE
Main pages updates: New section 'Who we are'

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#104]
So quite a few things have changed on the website designs that didn't get captured here. I'm breaking them into a few issues.

Most up to date page mock-up:
https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/screen/563447da-d7d4-4adc-9739-b8cf99a0687c/Version-4-23-04-2020?fullscreen

This issue is for this section 'Who we are' which is a new section:

<img width="674" alt="Screenshot 2020-05-19 at 19 37 37" src="https://user-images.githubusercontent.com/11681324/82365194-3eaa8580-9a08-11ea-92c8-e5529becdffd.png">

- Add this new section between the 'our mission' and 'events
- Link to image: https://drive.google.com/open?id=1CRM6S-iWuVptFG37HCks5N_6xWffY1FV
- Copy to read 'FOSS Responders is a working group of volunteers from various organizations. '
- Button copy 'Find out more about us'
- Button icon: https://drive.google.com/open?id=1yuTN5x1SreQ8A-CrZWkrJeYOmniQ0Xtv
- Button links out to: https://fossresponders.com/about/

**Comment by Erioldoesdesign** [comment]
@alisonjudy @awright I'm not sure if you'd like more copy in the written part of this section?

**Comment by awright** [comment]
Yeah... we probably should write something more in depth. How about
something like this? (please edit with any wordsmithing)

FOSS Responders came together to support and celebrate our Free and Open
Source Community affected by the COVID19 economic fall out. Learn more
about how you can help. And come join us!

**Comment by alisonjudy** [comment]
**edit (since this is the call out to get people to the about us page):**
FOSS Responders is a group of individuals who came together to support and celebrate our Free and Open Source Community affected by the COVID-19 economic fallout. Learn more
about us!

**Then on the about us page we can post @awright's version:** 
FOSS Responders came together to support and celebrate our Free and Open
Source Community affected by the COVID-19 economic fallout. Learn
more about the team, how you can help, and how to join us!

^^ assuming that there's a button for people to volunteer/learn how to help. If not, we can change the last line from: " Learn more about the team, how you can help, and how to join us!" to "Meet the team!"

**Comment by RichardLitt** [comment]
Updated and pushed! I think we got this covered. Not sure we have a way for people to get involved at the moment; but also not sure we need that?
