### ISSUE TITLE
Create the 'Foss Responders' Personas that we serve

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#17]
We'd like to document in a collaborative and open way the people that we serve through FOSS responders in a kind of 'persona' format.

Info on 'user personas' I typically refer to:
https://uxplanet.org/how-to-create-personas-step-by-step-guide-303d7b0d81b4
https://www.nngroup.com/topic/personas/
https://www.interaction-design.org/literature/article/personas-why-and-how-you-should-use-them 

Off the top of my head I can think of:

### 1. Individuals needing income/financial support due to conference/event cancellations
* Individuals on low income
* Individuals on freelance/un-formal salaried employment
* Students and career changers looking for connections and/or work immediately
* Individuals or small OSS projects looking for their first funding/break at an event
   
### 2. Individuals wanting to help/support
* Students and career changers looking for connections and/or work but not immediately
* Community connection & cohesion
* Individuals/OSS orgs/Maintainers looking for contribution support and/or signal boosting
    
### 3. Organisations and companies wanting to support
* Large orgs/companies with dedicated funds for this kind of cause
* Large orgs/companies with restricted funds for this kind of cause
* Medium orgs/companies with either funds or people-power to help
* Small orgs/companies with either funds or people-power to help
* Orgs/companies looking to signal boost or offer non-financial support

### 4. Organisations and companies looking to hire/recruit contributors/maintainers
* Large orgs/companies looking to hire/recruit contributors/maintainers
* Medium orgs/companies looking to hire/recruit contributors/maintainers
* Small orgs/companies looking to hire/recruit contributors/maintainers
* Very new projects looking to hire/recruit contributors/maintainers

## A google slides template that could help us: 

https://docs.google.com/presentation/d/1eOo9r8WM5BwW6ShOZxwT7ukiTcXOO2btLAW4q6y7p-0/edit?usp=sharing

Feel free to edit/amend add detail to the google template or offer completely different ways of doing personas. 
Markdown Persona templates that could live in the repo very welcome! :)

**Comment by Erioldoesdesign** [comment]
Via the meeting today additional personas could be:

- People/organisations that want to offer non-financial support but support from a services/skills pov

**Comment by awright** [comment]
I think you capture this here, though it's a little hard for me to parse. For me, I see two general "buckets" of personas with more nuance within each one. 

The first group are those who need help and the second group are those wanting to give. Within each bucket are both individuals and organizations. 

(I will copy and paste the 4 you outline here with inline comments.)

**Comment by awright** [comment]
> ### 1. Individuals needing income/financial support due to conference/event cancellations

The individual request is not necessarily or solely due to conference cancellations. It might be because a person's work dried up because their employer needed to make cutbacks. The economic breadth of the coronavirus response has a much larger footprint than conferences (e.g., my brother had to lay off 5 employees from his open source law company this week). Do we want to capture and speak to those personas as well?

> * Individuals on low income

I don't 100% feel comfortable with this language, since income is a relative thing. High income people may also be hit in ways valid to support (e.g., increased childcare responsibilities). Do you think we should leave this characteristic out? 

> * Individuals on freelance/un-formal salaried employment

Formal employees whom are let go too. 

> * Students and career changers looking for connections and/or work immediately

Not sure I understand the priority here. 

> * Individuals or small OSS projects looking for their first funding/break at an event
> 
> ### 2. Individuals wanting to help/support

I see this in the 2nd bucket. One characteristic potentially missing are people part of the community that are in more secure situations that want to help. They have access to contribute, whether time or money. 

> * Students and career changers looking for connections and/or work but not immediately

Not sure I see the priority here. 

> * Community connection & cohesion
> * Individuals/OSS orgs/Maintainers looking for contribution support and/or signal boosting

I think specific to those economically affected by coronavirus response?
> 
> ### 3. Organisations and companies wanting to support

Also in 2nd bucket 
> * Large orgs/companies with dedicated funds for this kind of cause

My take away from our meeting today is that the persona for organizations looking to support is not large orgs but rather smaller ones. Large orgs will probably give directly to foundations. 

> * Large orgs/companies with restricted funds for this kind of cause
> * Medium orgs/companies with either funds or people-power to help
> * Small orgs/companies with either funds or people-power to help
> * Orgs/companies looking to signal boost or offer non-financial support
> 
> ### 4. Organisations and companies looking to hire/recruit contributors/maintainers

This is an interesting persona and would love to hear others' take. I had not considered this one. 

> * Large orgs/companies looking to hire/recruit contributors/maintainers
> * Medium orgs/companies looking to hire/recruit contributors/maintainers
> * Small orgs/companies looking to hire/recruit contributors/maintainers
> * Very new projects looking to hire/recruit contributors/maintainers

One persona I see missing are small organizations looking for funding. This could be a smaller event who's entire sustainability comes from sponsorships and ticket sales, or it can be a 5 person company who's federal contract dried up because gov't resources need to be placed towards response. The small orgs that maintain others I see as a potential persona 
> 
> ## A google slides template that could help us:
> https://docs.google.com/presentation/d/1eOo9r8WM5BwW6ShOZxwT7ukiTcXOO2btLAW4q6y7p-0/edit?usp=sharing
> 
> Feel free to edit/amend add detail to the google template or offer completely different ways of doing personas.
> Markdown Persona templates that could live in the repo very welcome! :)

**Comment by awright** [comment]
I think I'm getting a better sense of the personas we're serving. Our focus, at least for the moment, seems to be 1) organizations with lost revenue due to cancelled or changed event and 2) individual contributors effected by such event change.

**Comment by RichardLitt** [comment]
Pretty sure we got this, too.
