### ISSUE TITLE
Embed the Conferences airtable

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#52]
This is missing completely from the current website! Let's work on getting it back in.

**Comment by RichardLitt** [comment]
@Erioldoesdesign Not sure if just dumbly embedding it is the smartest. I've asked Alison to get me credentials so I can do that, anyway.

**Comment by Erioldoesdesign** [comment]
@RichardLitt hmmmm embedding eh?...hmmmm I would expect it would embed in a clunky way ala i-frames of ye olde internets.

In an ideal user-facing way I would want something like the airtable being used a data source to populate a better formatted for our site 'table' style. But I would limit it to say...the 5 most recent entries and maybe select certain columns. The idea is we want to drive traffic somewhat to that table and rally info gathering and validation around that source rather than people coming to fossresponders to look at the embedded table.

Want me to do a mock-up of what I've babbled about above? Also any comments on my babble very appreciated! especially from the content focussed sub-group

**Comment by RichardLitt** [comment]
It sounds [hypothetically possible](https://community.airtable.com/t/view-last-record-only/11687) to make a view of only the most recent additions to the Airtable. I can also probably get these programmatically through the Airtable API. However, this will almost certainly involve a lot of JavaScript, and I don't know if I can do it on the client-side ... Yes, it can probably work. 

That certainly does push out the development timeline for this, though. :)

**Comment by Erioldoesdesign** [comment]
Stretch goal?

Super happy for now there being a good description and a link to the airtable rather than any kind of embedding. Unless there's a really strong argument for an easy embed

**Comment by RichardLitt** [comment]
Ok. I've added in the events lists on the site in two places, for now.
