### ISSUE TITLE
Debate color switches for toggles on first two Offer Help buttons

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#68]
I think that the colors are off, but this was as designed. Should I switch them?

**Comment by Erioldoesdesign** [comment]
Do you mean the fact that in the mockup it was blue then pink:
<img width="396" alt="Screenshot 2020-04-21 at 10 15 56" src="https://user-images.githubusercontent.com/11681324/79848573-291a4f80-83b9-11ea-9a3a-c2340ed621d6.png">


instead of pink then blue:
<img width="438" alt="Screenshot 2020-04-21 at 10 16 00" src="https://user-images.githubusercontent.com/11681324/79848581-2ddf0380-83b9-11ea-90e2-2b22902b45ce.png">


That was definitely a design mistake that I corrected in subsequent XD mockups. There's also another mistake I made when choosing the background blue colour, after checking on AAA accessibility I change the base blue to #2292CE when text is overlayed (so these rectangles and buttons) so that it is accessible.

However! we'll keep this blue: #58B2E4 (which is lighter) for illustrations and other uses that don't affect accessibility directly

**Comment by RichardLitt** [comment]
Ha! Well, this is fixed now. :)
