### ISSUE TITLE
Add an event banner for the May 1 event

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#69]
As needed.

**Comment by awright** [comment]
YAY!!! Now we just need to make the event.... ;)

**Comment by Erioldoesdesign** [comment]
@awright By 'banner' do you mean a graphical banner? You need me on this?

**Comment by awright** [comment]
we want to announce the may 22nd event higher up on the website. @RichardLitt suggested a banner, which he said he could implement rather roughly in the short term but would be great to have something nicer in the longer term. thoughts all?

**Comment by RichardLitt** [comment]
A page would also work, as well as a banner, if we can get designs for it. @Erioldoesdesign Let me know what either of these would look like.

**Comment by Erioldoesdesign** [comment]
For big important announcements
<img width="791" alt="Screenshot 2020-04-21 at 10 06 13" src="https://user-images.githubusercontent.com/11681324/79847567-d2604600-83b7-11ea-8d0c-a183b5f2f158.png">
 I would suggest something like this at the top of the webpage: https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/

It's simple but that's good because it's informational and call to action focussed :)

Button would click through to:https://blog.opencollective.com/foss-funding-event/

**Comment by Erioldoesdesign** [comment]
Note: this yellow background doesn't overlay the current content, but 'pushes' it down

**Comment by RichardLitt** [comment]
Thank you! I can implement this rather easily.

**Comment by awright** [comment]
awesome. thanks!
